IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Group')
BEGIN
    ALTER TABLE [Group]
    ADD [Name] NVARCHAR(50) NOT NULL DEFAULT ''
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Project')
BEGIN
    ALTER TABLE [Project]
    ADD CONSTRAINT Unique_ProjectNumber UNIQUE (ProjectNumber) 
END 

